name:                haskell-aws-secretsmanager
version:             0.1.0
github:              "githubuser/haskell-aws-secretsmanager"
license:             MIT
author:              "Shunsuke Masuda"
copyright:           "2019 Shunsuke Masuda"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-aws-secretsmanager#readme>

dependencies:
- base >= 4.7 && < 5
- amazonka-secretsmanager
- lens
- monad-control
- transformers
- text
- amazonka
- aeson
- string-conversions
- cached-io

library:
  source-dirs: src

executables:
  haskell-aws-secretsmanager-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -freverse-errors
    dependencies:
    - haskell-aws-secretsmanager
